export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ADD_PHOTO_START = 'ADD_PHOTO_START';
export const ADD_PHOTO_SUCCESS = 'ADD_PHOTO_SUCCESS';
export const ADD_PHOTO_FAIL = 'ADD_PHOTO_FAIL';
export const ADD_PHOTO_INIT = 'ADD_PHOTO_INIT';
export const PURCHASE_PHOTO = 'PURCHASE_PHOTO';
export const FETCH_PHOTO_START = 'FETCH_PHOTO_START';
export const FETCH_PHOTO_SUCCESS = 'FETCH_PHOTO_SUCCESS';
export const FETCH_PHOTO_FAIL = 'FETCH_PHOTO_FAIL';
export const UPDATE_PHOTO_REQUEST = 'PHOTO_UPDATE_REQUEST';
export const UPDATE_PHOTO_SUCCESS = 'PHOTO_UPDATE_SUCCESS';
export const UPDATE_PHOTO_FAIL = 'PHOTO_UPDATE_FAIL';
export const UPDATE_PHOTO_RESET = 'PHOTO_UPDATE_RESET';
